### ISSUE TITLE
Change the HPCC Info title to include the logo

### ISSUE THREAD

**Issue by arjunachala** [hpcc-systems/HPCCInfo#53]
![image](https://user-images.githubusercontent.com/999180/27199358-bc190aca-51e3-11e7-8b2f-a57e633c990c.png)

to

![image](https://user-images.githubusercontent.com/999180/27199429-e84987dc-51e3-11e7-8b45-1bf9e7001482.png)
 
and add the title if it exists like "HPCC Info - [title]"

**Comment by dineshshetye** [comment]
@arjunachala the assumption here was that the user can double click on the label and edit it. The new label is used as a title for the workbook. I have change the label from "Welcome to HPCCInfo Application" to "HPCCInfo"

**Comment by dineshshetye** [comment]
Double click and Edit the title must be disabled. If the user needs to change the Workbook title they should go through the Edit Workbook workflow.
